<?php
/**
 * @file
 * Make a menu or some other element on the page stick on top when you scroll
 * down
 */

/**
 * Implements hook_init().
 */
function stickynav_init() {
  global $user, $theme;
  // Check if user has an exclusion role.
  $excluded_roles = config_get('stickynav.settings', 'stickynav-roles-' . $theme);
  if (isset($excluded_roles) && array_intersect_key($excluded_roles, $user->roles)) {
    return;
  }
  $selector = config_get('stickynav.settings', 'stickynav-selector-' . $theme);
  $offset_selector = config_get('stickynav.settings', 'stickynav-offset-selector-' . $theme);
  $custom_offset = config_get('stickynav.settings', 'stickynav-custom-offset' . $theme);
  // Will only add the sticky nav assets if the theme and selector are set.
  if (config_get('stickynav.settings', 'stickynav-enabled-' . $theme) && trim($selector)) {
    backdrop_add_css(backdrop_get_path('module', 'stickynav') .
      '/css/stickynav.css');
    backdrop_add_js(backdrop_get_path('module', 'stickynav') . '/js/stickynav.js');
    $settings = array(
      'stickynav' => array(
        'selector' => check_plain($selector),
        'offsets' => array(
          'selector' => check_plain($offset_selector),
          'custom_offset' => check_plain($custom_offset),
        ),
      ),
    );
    backdrop_add_js($settings, 'setting');
  }
}

/**
 * Implements hook_permission().
 */
function stickynav_permission() {
  return array(
    'administer stickynav' => array(
      'title' => t('Administer Sticky Nav'),
      'description' => t('Permission to activate and manage Sticky Nav.'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function stickynav_menu() {
  $items['admin/config/user-interface/stickynav'] = array(
    'title' => 'Sticky Nav Settings',
    'description' => 'Settings of sticky navigation on your website',
    'page callback' => 'backdrop_get_form',
    'page arguments' => array('stickynav_admin_form'),
    'access callback' => 'user_access',
    'access arguments' => array('administer stickynav'),
    'file' => 'stickynav.admin.inc',
  );
  return $items;
}

/**
  * Implements hook_config_info().
  */
function stickynav_config_info() {
  $prefixes['stickynav.settings'] = array(
    'label' => t('Sticky Navigation settings'),
    'group' => t('Configuration'),
  );
  return $prefixes;
}