<?php
/**
 * @file
 * Make a menu or some other element on the page stick on top when you scroll
 * down
 */

/**
 * Implements hook_init().
 */
function stickynav_init() {
  /*
  Check if permissions are enabled and if the user has the
  permission to use sticky navigation.
  */
  if (variable_get('stickynav-permissions', FALSE) && !user_access('use stickynav')) {
    return;
  }
  global $theme;
  $selector = variable_get('stickynav-selector-' . $theme, '');
  // Will only add the sticky nav assets if the theme and selector are set.
  if (variable_get('stickynav-enabled-' . $theme, FALSE) && trim($selector)) {
    drupal_add_css(drupal_get_path('module', 'stickynav') .
      '/css/stickynav.css');
    drupal_add_js(drupal_get_path('module', 'stickynav') . '/js/stickynav.js');
    $settings = array(
      'stickynav' => array(
        'selector' => check_plain($selector),
      ),
    );
    drupal_add_js($settings, 'setting');
  }
}

/**
 * Implements hook_permission().
 */
function stickynav_permission() {
  return array(
    'administer stickynav' => array(
      'title' => t('Administer Sticky Nav'),
      'description' => t('Permission to activate and manage Sticky Nav.'),
    ),
    'use stickynav' => array(
      'title' => t('Use Sticky Nav'),
      'description' => t('Permission to use the sticky navigation.'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function stickynav_menu() {
  $items['admin/config/user-interface/stickynav'] = array(
    'title' => 'Sticky Nav Settings',
    'description' => 'Settings of sticky navigation on your website',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('stickynav_admin_form'),
    'access callback' => 'user_access',
    'access arguments' => array('administer stickynav'),
    'file' => 'admin/stickynav.admin.inc',
  );
  return $items;
}
